### ISSUE TITLE
[RFE] Add recommended targets to Archetypes

### ISSUE THREAD

**Issue by rromannissen** [konveyor/enhancements#147] opened 2023-12-18 10:38 UTC
In large scale migration projects, it is often important to provide guidance for developers on what could be the most suitable migration path for a given application based on its taxonomy. Since archetypes have become a first class entity to classify applications in different types or categories, it makes sense to associate those recommendations with them. At a very high level, this enhancement would include the following:

- Allow architects to associate recommended migration targets to a given archetype, including custom migration targets.
- When analyzing a single application, the UI would highlight the recommended migration targets somehow, but it would still be up to the user to decide which should be selected.
- When analyzing multiple applications, recommended targets will only be highlighted if all applications belong to the same archetype.

This enhancement would be especially interesting for the Backstage/Janus integration use case, as it would allow organizations to enforce certain migration paths from their IDP. For that case:

- Discovery analysis would be automatically run on the application.
- Based on that discovery, the application would likely be associated with an archetype.
- Based on the archetype, the user would be presented (maybe only) with the recommended migration paths for analysis.

**Comment by rromannissen** [comment] 2023-12-18 10:38
@dymurray @jortel @JustinXHale for your consideration

**Comment by JustinXHale** [comment] 2024-01-09 16:29
[Figma](https://www.figma.com/proto/BuXtFaxk5jy8H0AD0NkkL7/MTA-Web-Console-%2B-Tackle?type=design&node-id=110-4492&t=uaeBApO0Dl1SN0cx-1&scaling=min-zoom&page-id=110%3A4491&starting-point-node-id=110%3A4492&mode=design)

![image](https://github.com/konveyor/enhancements/assets/91554933/6bf58809-0872-49d8-b704-be473792dfa6)

**Comment by dymurray** [comment] 2024-08-01 14:53
Closing as duplicate of https://github.com/konveyor/enhancements/issues/186

**Closed by dymurray** 2024-08-01 14:53 UTC
Labels: RFE
